# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k0RLsbD3UiBaP_zDQKACU-3xVLcPJfBy
"""

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

from google.colab import files
arq = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")
df.head()

df["custo"] = df["Custo Unitário"].mul(df["Quantidade"])
round(df["custo"].sum(), 2)

df["lucro"]  = df["Valor Venda"] - df["custo"]
round(df["lucro"].sum(),2)

df["Valor Venda"].sum()

pd.options.display.float_format = '{:20,.2f}'.format

df.groupby([df["Data Venda"].dt.year, "Marca"])["lucro"].sum()

lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["lucro"].sum().reset_index()
lucro_ano

lucro_ano.groupby(lucro_ano["Data Venda"])["lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Marca");

lucro_ano.to_csv("df_lucro_ano_marca.csv", index=False)
lucro_ano.to_excel("df_lucro_ano_marca.xlsx", index=False)